package com.lottery.model;
// default package

// Generated 2015-9-13 13:41:05 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.serializer.SerializerFeature;

/**
 * Lotterylog generated by hbm2java
 */
@Entity
@Table(name = "lotterylog", catalog = "lottery")
public class Lotterylog implements java.io.Serializable {

	private Integer id;
	private Integer lotteryId;
	private String qishu;
	private Integer num1;
	private Integer num2;
	private Integer num3;
	private Integer sum;
	private String size;
	private String single;
	private Integer state;

	public Lotterylog() {
	}

	public Lotterylog(Integer lotteryId, String qishu, Integer num1, Integer num2, Integer num3, Integer sum,
			String size, String single, Integer state) {
		this.lotteryId = lotteryId;
		this.qishu = qishu;
		this.num1 = num1;
		this.num2 = num2;
		this.num3 = num3;
		this.sum = sum;
		this.size = size;
		this.single = single;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lotteryId")
	public Integer getLotteryId() {
		return this.lotteryId;
	}

	public void setLotteryId(Integer lotteryId) {
		this.lotteryId = lotteryId;
	}

	@Column(name = "qishu", length = 64)
	public String getQishu() {
		return this.qishu;
	}

	public void setQishu(String qishu) {
		this.qishu = qishu;
	}

	@Column(name = "num1")
	public Integer getNum1() {
		return this.num1;
	}

	public void setNum1(Integer num1) {
		this.num1 = num1;
	}

	@Column(name = "num2")
	public Integer getNum2() {
		return this.num2;
	}

	public void setNum2(Integer num2) {
		this.num2 = num2;
	}

	@Column(name = "num3")
	public Integer getNum3() {
		return this.num3;
	}

	public void setNum3(Integer num3) {
		this.num3 = num3;
	}

	@Column(name = "sum")
	public Integer getSum() {
		return this.sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	@Column(name = "size", length = 12)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "single", length = 12)
	public String getSingle() {
		return this.single;
	}

	public void setSingle(String single) {
		this.single = single;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return JSONObject.toJSONString(this, SerializerFeature.WriteMapNullValue);
	}
}
