package com.lottery.model;
// default package

import static javax.persistence.GenerationType.IDENTITY;

// Generated 2015-9-13 13:41:05 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.serializer.SerializerFeature;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "lottery")
public class User implements java.io.Serializable {

	private Integer id;
	private String account;
	private String password;
	private String qq;
	private String phone;
	private String question;
	private String answer;
	private String drawPass;
	private Integer parentId;
	private String parentName;
	private String bankName;
	private String bankAccount;
	private String bankAddress;
	private String bankUser;
	private Integer type;
	private Integer state;
	private Date lastTime;

	public User() {
	}

	public User(String account, String password, String qq, String phone, String question, String answer,
			String drawPass, Integer parentId, String parentName, String bankName, String bankAccount,
			String bankAddress, String bankUser, Integer type, Integer state, Date lastTime) {
		this.account = account;
		this.password = password;
		this.qq = qq;
		this.phone = phone;
		this.question = question;
		this.answer = answer;
		this.drawPass = drawPass;
		this.parentId = parentId;
		this.parentName = parentName;
		this.bankName = bankName;
		this.bankAccount = bankAccount;
		this.bankAddress = bankAddress;
		this.bankUser = bankUser;
		this.type = type;
		this.state = state;
		this.lastTime = lastTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account", length = 32)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "qq", length = 16)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "question", length = 125)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "answer", length = 125)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "drawPass", length = 10)
	public String getDrawPass() {
		return this.drawPass;
	}

	public void setDrawPass(String drawPass) {
		this.drawPass = drawPass;
	}

	@Column(name = "parentId")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parentName", length = 32)
	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	@Column(name = "bankName", length = 32)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bankAccount", length = 32)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "bankAddress", length = 32)
	public String getBankAddress() {
		return this.bankAddress;
	}

	public void setBankAddress(String bankAddress) {
		this.bankAddress = bankAddress;
	}

	@Column(name = "bankUser", length = 32)
	public String getBankUser() {
		return this.bankUser;
	}

	public void setBankUser(String bankUser) {
		this.bankUser = bankUser;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastTime", length = 19)
	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	@Override
	public String toString() {
		return JSONObject.toJSONString(this, SerializerFeature.WriteMapNullValue);
	}
}
