package com.lottery.model;
// default package

// Generated 2015-9-13 13:41:05 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.serializer.SerializerFeature;

/**
 * Userbuylog generated by hbm2java
 */
@Entity
@Table(name = "userbuylog", catalog = "lottery")
public class Userbuylog implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String userName;
	private Integer lotteryId;
	private String lotteryName;
	private String periNum;
	private Date addTime;
	private Float money;
	private Float winMoney;
	private Integer state;
	private String num;
	private Integer playId;
	private String playNum;

	public Userbuylog() {
	}

	public Userbuylog(String userId, String userName, Integer lotteryId, String lotteryName, String periNum,
			Date addTime, Float money, Float winMoney, Integer state, String num, Integer playId, String playNum) {
		this.userId = userId;
		this.userName = userName;
		this.lotteryId = lotteryId;
		this.lotteryName = lotteryName;
		this.periNum = periNum;
		this.addTime = addTime;
		this.money = money;
		this.winMoney = winMoney;
		this.state = state;
		this.num = num;
		this.playId = playId;
		this.playNum = playNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 32)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "lotteryId")
	public Integer getLotteryId() {
		return this.lotteryId;
	}

	public void setLotteryId(Integer lotteryId) {
		this.lotteryId = lotteryId;
	}

	@Column(name = "lotteryName", length = 32)
	public String getLotteryName() {
		return this.lotteryName;
	}

	public void setLotteryName(String lotteryName) {
		this.lotteryName = lotteryName;
	}

	@Column(name = "periNum", length = 32)
	public String getPeriNum() {
		return this.periNum;
	}

	public void setPeriNum(String periNum) {
		this.periNum = periNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "addTime", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "money", precision = 12, scale = 0)
	public Float getMoney() {
		return this.money;
	}

	public void setMoney(Float money) {
		this.money = money;
	}

	@Column(name = "winMoney", precision = 12, scale = 0)
	public Float getWinMoney() {
		return this.winMoney;
	}

	public void setWinMoney(Float winMoney) {
		this.winMoney = winMoney;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "num", length = 32)
	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	@Column(name = "playId")
	public Integer getPlayId() {
		return this.playId;
	}

	public void setPlayId(Integer playId) {
		this.playId = playId;
	}

	@Column(name = "playNum", length = 64)
	public String getPlayNum() {
		return this.playNum;
	}

	public void setPlayNum(String playNum) {
		this.playNum = playNum;
	}

	@Override
	public String toString() {
		return JSONObject.toJSONString(this, SerializerFeature.WriteMapNullValue);
	}
}
