package com.sb.hyh.po;
// Generated 2016-6-17 10:55:29 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OpenapiTebiechengxushenqing generated by hbm2java
 */
@Entity
@Table(name = "OPENAPI_TEBIECHENGXUSHENQING", schema = "NEW_BPP")
public class OpenapiTebiechengxushenqing implements Serializable {

	private String id;
	private String yxtywlsh;
	private String slh;
	private long sort;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String remarks;
	private char delFlag;
	private String sjbbh;
	private String blbm;
	private String zrsj;
	private String xh;
	private String tbcxzl;
	private String tbcxzlmc;
	private String tbcxpzr;
	private Date tbcxksrq;
	private String tbcxsx;
	private String tbcxsxdw;
	private String bz;
	private String byzda;
	private String byzdb;

	public OpenapiTebiechengxushenqing() {
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "YXTYWLSH", nullable = false, length = 64)
	public String getYxtywlsh() {
		return this.yxtywlsh;
	}

	public void setYxtywlsh(String yxtywlsh) {
		this.yxtywlsh = yxtywlsh;
	}

	@Column(name = "SLH", length = 64)
	public String getSlh() {
		return this.slh;
	}

	public void setSlh(String slh) {
		this.slh = slh;
	}

	@Column(name = "SORT", nullable = false, precision = 10, scale = 0)
	public long getSort() {
		return this.sort;
	}

	public void setSort(long sort) {
		this.sort = sort;
	}

	@Column(name = "CREATE_BY", length = 64)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "CREATE_DATE")
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 64)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "UPDATE_DATE")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "DEL_FLAG", nullable = false, length = 1)
	public char getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(char delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "SJBBH", nullable = false, length = 100)
	public String getSjbbh() {
		return this.sjbbh;
	}

	public void setSjbbh(String sjbbh) {
		this.sjbbh = sjbbh;
	}

	@Column(name = "BLBM", nullable = false, length = 2)
	public String getBlbm() {
		return this.blbm;
	}

	public void setBlbm(String blbm) {
		this.blbm = blbm;
	}

	@Column(name = "ZRSJ", nullable = false, length = 200)
	public String getZrsj() {
		return this.zrsj;
	}

	public void setZrsj(String zrsj) {
		this.zrsj = zrsj;
	}

	@Column(name = "XH", nullable = false, length = 2)
	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	@Column(name = "TBCXZL", nullable = false, length = 2)
	public String getTbcxzl() {
		return this.tbcxzl;
	}

	public void setTbcxzl(String tbcxzl) {
		this.tbcxzl = tbcxzl;
	}

	@Column(name = "TBCXZLMC", nullable = false, length = 200)
	public String getTbcxzlmc() {
		return this.tbcxzlmc;
	}

	public void setTbcxzlmc(String tbcxzlmc) {
		this.tbcxzlmc = tbcxzlmc;
	}

	@Column(name = "TBCXPZR", nullable = false, length = 100)
	public String getTbcxpzr() {
		return this.tbcxpzr;
	}

	public void setTbcxpzr(String tbcxpzr) {
		this.tbcxpzr = tbcxpzr;
	}

	@Column(name = "TBCXKSRQ", nullable = false)
	public Date getTbcxksrq() {
		return this.tbcxksrq;
	}

	public void setTbcxksrq(Date tbcxksrq) {
		this.tbcxksrq = tbcxksrq;
	}

	@Column(name = "TBCXSX", nullable = false, length = 3)
	public String getTbcxsx() {
		return this.tbcxsx;
	}

	public void setTbcxsx(String tbcxsx) {
		this.tbcxsx = tbcxsx;
	}

	@Column(name = "TBCXSXDW", nullable = false, length = 3)
	public String getTbcxsxdw() {
		return this.tbcxsxdw;
	}

	public void setTbcxsxdw(String tbcxsxdw) {
		this.tbcxsxdw = tbcxsxdw;
	}

	@Column(name = "BZ", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "BYZDA", length = 100)
	public String getByzda() {
		return this.byzda;
	}

	public void setByzda(String byzda) {
		this.byzda = byzda;
	}

	@Column(name = "BYZDB", length = 100)
	public String getByzdb() {
		return this.byzdb;
	}

	public void setByzdb(String byzdb) {
		this.byzdb = byzdb;
	}

}
