package com.sb.hyh.po;
// Generated 2016-6-17 10:55:29 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OpenapiBanjie generated by hbm2java
 */
@Entity
@Table(name = "OPENAPI_BANJIE", schema = "NEW_BPP")
public class OpenapiBanjie implements java.io.Serializable {

	private String id;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String remarks;
	private String yxtywlsh;
	private String slh;
	private char delFlag;
	private String sjbbh;
	private String blbm;
	private String zrsj;
	private Date bjsj;
	private String bjzt;
	private String byxkyy;
	private String yqyy;
	private String bz;
	private String byzda;
	private String byzdb;

	public OpenapiBanjie() {
	}

	public OpenapiBanjie(String id, String yxtywlsh, char delFlag, String sjbbh, String blbm, String zrsj,
			Date bjsj, String bjzt, String byxkyy, String yqyy) {
		this.id = id;
		this.yxtywlsh = yxtywlsh;
		this.delFlag = delFlag;
		this.sjbbh = sjbbh;
		this.blbm = blbm;
		this.zrsj = zrsj;
		this.bjsj = bjsj;
		this.bjzt = bjzt;
		this.byxkyy = byxkyy;
		this.yqyy = yqyy;
	}

	public OpenapiBanjie(String id, String createBy, Date createDate, String updateBy, Date updateDate,
			String remarks, String yxtywlsh, String slh, char delFlag, String sjbbh, String blbm, String zrsj,
			Date bjsj, String bjzt, String byxkyy, String yqyy, String bz, String byzda, String byzdb) {
		this.id = id;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.remarks = remarks;
		this.yxtywlsh = yxtywlsh;
		this.slh = slh;
		this.delFlag = delFlag;
		this.sjbbh = sjbbh;
		this.blbm = blbm;
		this.zrsj = zrsj;
		this.bjsj = bjsj;
		this.bjzt = bjzt;
		this.byxkyy = byxkyy;
		this.yqyy = yqyy;
		this.bz = bz;
		this.byzda = byzda;
		this.byzdb = byzdb;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CREATE_BY", length = 64)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "CREATE_DATE")
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 64)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "UPDATE_DATE")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "YXTYWLSH", nullable = false, length = 64)
	public String getYxtywlsh() {
		return this.yxtywlsh;
	}

	public void setYxtywlsh(String yxtywlsh) {
		this.yxtywlsh = yxtywlsh;
	}

	@Column(name = "SLH", length = 64)
	public String getSlh() {
		return this.slh;
	}

	public void setSlh(String slh) {
		this.slh = slh;
	}

	@Column(name = "DEL_FLAG", nullable = false, length = 1)
	public char getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(char delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "SJBBH", nullable = false, length = 100)
	public String getSjbbh() {
		return this.sjbbh;
	}

	public void setSjbbh(String sjbbh) {
		this.sjbbh = sjbbh;
	}

	@Column(name = "BLBM", nullable = false, length = 2)
	public String getBlbm() {
		return this.blbm;
	}

	public void setBlbm(String blbm) {
		this.blbm = blbm;
	}

	@Column(name = "ZRSJ", nullable = false, length = 200)
	public String getZrsj() {
		return this.zrsj;
	}

	public void setZrsj(String zrsj) {
		this.zrsj = zrsj;
	}

	@Column(name = "BJSJ", nullable = false)
	public Date getBjsj() {
		return this.bjsj;
	}

	public void setBjsj(Date bjsj) {
		this.bjsj = bjsj;
	}

	@Column(name = "BJZT", nullable = false, length = 2)
	public String getBjzt() {
		return this.bjzt;
	}

	public void setBjzt(String bjzt) {
		this.bjzt = bjzt;
	}

	@Column(name = "BYXKYY", nullable = false, length = 1000)
	public String getByxkyy() {
		return this.byxkyy;
	}

	public void setByxkyy(String byxkyy) {
		this.byxkyy = byxkyy;
	}

	@Column(name = "YQYY", nullable = false, length = 1000)
	public String getYqyy() {
		return this.yqyy;
	}

	public void setYqyy(String yqyy) {
		this.yqyy = yqyy;
	}

	@Column(name = "BZ", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "BYZDA", length = 100)
	public String getByzda() {
		return this.byzda;
	}

	public void setByzda(String byzda) {
		this.byzda = byzda;
	}

	@Column(name = "BYZDB", length = 100)
	public String getByzdb() {
		return this.byzdb;
	}

	public void setByzdb(String byzdb) {
		this.byzdb = byzdb;
	}

}
